/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "cncos.io/box-controller/pkg/apis/boxstatefulset/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBoxStatefulSets implements BoxStatefulSetInterface
type FakeBoxStatefulSets struct {
	Fake *FakeCncosV1alpha1
	ns   string
}

var boxstatefulsetsResource = v1alpha1.SchemeGroupVersion.WithResource("boxstatefulsets")

var boxstatefulsetsKind = v1alpha1.SchemeGroupVersion.WithKind("BoxStatefulSet")

// Get takes name of the boxStatefulSet, and returns the corresponding boxStatefulSet object, and an error if there is any.
func (c *FakeBoxStatefulSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BoxStatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(boxstatefulsetsResource, c.ns, name), &v1alpha1.BoxStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BoxStatefulSet), err
}

// List takes label and field selectors, and returns the list of BoxStatefulSets that match those selectors.
func (c *FakeBoxStatefulSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BoxStatefulSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(boxstatefulsetsResource, boxstatefulsetsKind, c.ns, opts), &v1alpha1.BoxStatefulSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BoxStatefulSetList{ListMeta: obj.(*v1alpha1.BoxStatefulSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.BoxStatefulSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested boxStatefulSets.
func (c *FakeBoxStatefulSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(boxstatefulsetsResource, c.ns, opts))

}

// Create takes the representation of a boxStatefulSet and creates it.  Returns the server's representation of the boxStatefulSet, and an error, if there is any.
func (c *FakeBoxStatefulSets) Create(ctx context.Context, boxStatefulSet *v1alpha1.BoxStatefulSet, opts v1.CreateOptions) (result *v1alpha1.BoxStatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(boxstatefulsetsResource, c.ns, boxStatefulSet), &v1alpha1.BoxStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BoxStatefulSet), err
}

// Update takes the representation of a boxStatefulSet and updates it. Returns the server's representation of the boxStatefulSet, and an error, if there is any.
func (c *FakeBoxStatefulSets) Update(ctx context.Context, boxStatefulSet *v1alpha1.BoxStatefulSet, opts v1.UpdateOptions) (result *v1alpha1.BoxStatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(boxstatefulsetsResource, c.ns, boxStatefulSet), &v1alpha1.BoxStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BoxStatefulSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBoxStatefulSets) UpdateStatus(ctx context.Context, boxStatefulSet *v1alpha1.BoxStatefulSet, opts v1.UpdateOptions) (*v1alpha1.BoxStatefulSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(boxstatefulsetsResource, "status", c.ns, boxStatefulSet), &v1alpha1.BoxStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BoxStatefulSet), err
}

// Delete takes name of the boxStatefulSet and deletes it. Returns an error if one occurs.
func (c *FakeBoxStatefulSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(boxstatefulsetsResource, c.ns, name, opts), &v1alpha1.BoxStatefulSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBoxStatefulSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(boxstatefulsetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BoxStatefulSetList{})
	return err
}

// Patch applies the patch and returns the patched boxStatefulSet.
func (c *FakeBoxStatefulSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BoxStatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(boxstatefulsetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.BoxStatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BoxStatefulSet), err
}
