/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "cncos.io/box-controller/pkg/apis/box/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBoxes implements BoxInterface
type FakeBoxes struct {
	Fake *FakeCncosV1alpha1
	ns   string
}

var boxesResource = v1alpha1.SchemeGroupVersion.WithResource("boxes")

var boxesKind = v1alpha1.SchemeGroupVersion.WithKind("Box")

// Get takes name of the box, and returns the corresponding box object, and an error if there is any.
func (c *FakeBoxes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Box, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(boxesResource, c.ns, name), &v1alpha1.Box{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Box), err
}

// List takes label and field selectors, and returns the list of Boxes that match those selectors.
func (c *FakeBoxes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BoxList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(boxesResource, boxesKind, c.ns, opts), &v1alpha1.BoxList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BoxList{ListMeta: obj.(*v1alpha1.BoxList).ListMeta}
	for _, item := range obj.(*v1alpha1.BoxList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested boxes.
func (c *FakeBoxes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(boxesResource, c.ns, opts))

}

// Create takes the representation of a box and creates it.  Returns the server's representation of the box, and an error, if there is any.
func (c *FakeBoxes) Create(ctx context.Context, box *v1alpha1.Box, opts v1.CreateOptions) (result *v1alpha1.Box, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(boxesResource, c.ns, box), &v1alpha1.Box{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Box), err
}

// Update takes the representation of a box and updates it. Returns the server's representation of the box, and an error, if there is any.
func (c *FakeBoxes) Update(ctx context.Context, box *v1alpha1.Box, opts v1.UpdateOptions) (result *v1alpha1.Box, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(boxesResource, c.ns, box), &v1alpha1.Box{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Box), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBoxes) UpdateStatus(ctx context.Context, box *v1alpha1.Box, opts v1.UpdateOptions) (*v1alpha1.Box, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(boxesResource, "status", c.ns, box), &v1alpha1.Box{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Box), err
}

// Delete takes name of the box and deletes it. Returns an error if one occurs.
func (c *FakeBoxes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(boxesResource, c.ns, name, opts), &v1alpha1.Box{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBoxes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(boxesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BoxList{})
	return err
}

// Patch applies the patch and returns the patched box.
func (c *FakeBoxes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Box, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(boxesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Box{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Box), err
}
