/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	boxv1alpha1 "cncos.io/box-controller/pkg/apis/box/v1alpha1"
	versioned "cncos.io/box-controller/pkg/box-generated/clientset/versioned"
	internalinterfaces "cncos.io/box-controller/pkg/box-generated/informers/externalversions/internalinterfaces"
	v1alpha1 "cncos.io/box-controller/pkg/box-generated/listers/box/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BoxInformer provides access to a shared informer and lister for
// Boxes.
type BoxInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.BoxLister
}

type boxInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBoxInformer constructs a new informer for Box type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBoxInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBoxInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBoxInformer constructs a new informer for Box type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBoxInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CncosV1alpha1().Boxes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CncosV1alpha1().Boxes(namespace).Watch(context.TODO(), options)
			},
		},
		&boxv1alpha1.Box{},
		resyncPeriod,
		indexers,
	)
}

func (f *boxInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBoxInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *boxInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&boxv1alpha1.Box{}, f.defaultInformer)
}

func (f *boxInformer) Lister() v1alpha1.BoxLister {
	return v1alpha1.NewBoxLister(f.Informer().GetIndexer())
}
