/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "cncos.io/box-controller/pkg/apis/boxstatefulset/v1alpha1"
	scheme "cncos.io/box-controller/pkg/boxstatefulset-generated/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BoxStatefulSetsGetter has a method to return a BoxStatefulSetInterface.
// A group's client should implement this interface.
type BoxStatefulSetsGetter interface {
	BoxStatefulSets(namespace string) BoxStatefulSetInterface
}

// BoxStatefulSetInterface has methods to work with BoxStatefulSet resources.
type BoxStatefulSetInterface interface {
	Create(ctx context.Context, boxStatefulSet *v1alpha1.BoxStatefulSet, opts v1.CreateOptions) (*v1alpha1.BoxStatefulSet, error)
	Update(ctx context.Context, boxStatefulSet *v1alpha1.BoxStatefulSet, opts v1.UpdateOptions) (*v1alpha1.BoxStatefulSet, error)
	UpdateStatus(ctx context.Context, boxStatefulSet *v1alpha1.BoxStatefulSet, opts v1.UpdateOptions) (*v1alpha1.BoxStatefulSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.BoxStatefulSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.BoxStatefulSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BoxStatefulSet, err error)
	BoxStatefulSetExpansion
}

// boxStatefulSets implements BoxStatefulSetInterface
type boxStatefulSets struct {
	client rest.Interface
	ns     string
}

// newBoxStatefulSets returns a BoxStatefulSets
func newBoxStatefulSets(c *CncosV1alpha1Client, namespace string) *boxStatefulSets {
	return &boxStatefulSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the boxStatefulSet, and returns the corresponding boxStatefulSet object, and an error if there is any.
func (c *boxStatefulSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BoxStatefulSet, err error) {
	result = &v1alpha1.BoxStatefulSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("boxstatefulsets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BoxStatefulSets that match those selectors.
func (c *boxStatefulSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BoxStatefulSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.BoxStatefulSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("boxstatefulsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested boxStatefulSets.
func (c *boxStatefulSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("boxstatefulsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a boxStatefulSet and creates it.  Returns the server's representation of the boxStatefulSet, and an error, if there is any.
func (c *boxStatefulSets) Create(ctx context.Context, boxStatefulSet *v1alpha1.BoxStatefulSet, opts v1.CreateOptions) (result *v1alpha1.BoxStatefulSet, err error) {
	result = &v1alpha1.BoxStatefulSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("boxstatefulsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(boxStatefulSet).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a boxStatefulSet and updates it. Returns the server's representation of the boxStatefulSet, and an error, if there is any.
func (c *boxStatefulSets) Update(ctx context.Context, boxStatefulSet *v1alpha1.BoxStatefulSet, opts v1.UpdateOptions) (result *v1alpha1.BoxStatefulSet, err error) {
	result = &v1alpha1.BoxStatefulSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("boxstatefulsets").
		Name(boxStatefulSet.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(boxStatefulSet).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *boxStatefulSets) UpdateStatus(ctx context.Context, boxStatefulSet *v1alpha1.BoxStatefulSet, opts v1.UpdateOptions) (result *v1alpha1.BoxStatefulSet, err error) {
	result = &v1alpha1.BoxStatefulSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("boxstatefulsets").
		Name(boxStatefulSet.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(boxStatefulSet).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the boxStatefulSet and deletes it. Returns an error if one occurs.
func (c *boxStatefulSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("boxstatefulsets").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *boxStatefulSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("boxstatefulsets").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched boxStatefulSet.
func (c *boxStatefulSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BoxStatefulSet, err error) {
	result = &v1alpha1.BoxStatefulSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("boxstatefulsets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
