apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-controller
  namespace: cncos-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-controller
rules:
- apiGroups: [""]
  resources: ["nodes", "configmaps"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-controller
subjects:
- kind: ServiceAccount
  name: resource-controller
  namespace: cncos-system
